
DROP TABLE IF EXISTS RepetableRead;
CREATE TABLE RepetableRead (
	Id INTEGER PRIMARY KEY NOT NULL,
	Value INTEGER NOT NULL
);

INSERT INTO RepetableRead VALUES(1,1);

SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
SELECT * FROM RepetableRead WHERE Id = 1;

SELECT pg_sleep(5);

SELECT * FROM RepetableRead WHERE Id = 1;
COMMIT; 