DROP TABLE IF EXISTS PhantomRead;
CREATE TABLE PhantomRead (
	Id INTEGER PRIMARY KEY NOT NULL,
	Value INTEGER NOT NULL
);

INSERT INTO PhantomRead VALUES(1,1);


SET TRANSACTION ISOLATION LEVEL READ COMMITTED;

SELECT * FROM PhantomRead;

SELECT pg_sleep(5); 

SELECT * FROM PhantomRead

COMMIT;