--Problem: dirty read

DROP TABLE IF EXISTS DirtyRead;
CREATE TABLE DirtyRead (
	Id INTEGER PRIMARY KEY NOT NULL,
	Value INTEGER NOT NULL
);

INSERT INTO DirtyRead VALUES(1,1);
SELECT * FROM DirtyRead;

BEGIN;
	UPDATE DirtyRead
	SET Value=10
	WHERE Id = 1;
	SELECT pg_sleep(10);
ROLLBACK;

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
BEGIN;
	SELECT * FROM DirtyRead;
	SELECT pg_sleep(10);
COMMIT;